coverage:
  status:
    # проверяет покрыты ли patch изменения тестами. Например, если делать PR и там коммит что-то добавил / изменил, 
    # но это не держится тестами (как хорошо должно держатся можно настроить), то будет ошибка, скрин: 
    # https://i.imgur.com/YqUaAZT.png
    patch:
      default:
        enabled: no
